feat(jte): Add explanation about removal of developers section (#789)
* feat(jte): Add explanation about removal of developers section

Add explanation for removing `developers` section when applying `UpgradeNextMajorParentVersion` recipe.

* **New Partial Template:**
  - Add `plugin-modernizer-core/src/main/jte/partials/remove-developers-tag.jte` to include common text about the removal of the `developers` tag.
* **Update PR Body for `RemoveDevelopersTag`:**
  - Modify `plugin-modernizer-core/src/main/jte/pr-body-RemoveDevelopersTag.jte` to include the new partial template using the `include` directive.
* **Update PR Body for `UpgradeNextMajorParentVersion`:**
  - Modify `plugin-modernizer-core/src/main/jte/pr-body-UpgradeNextMajorParentVersion.jte` to include the new partial template using the `include` directive.

* feat(jte): Add explanation about removal of developers section

Add explanation for removing `developers` section when applying `UpgradeNextMajorParentVersion` recipe.

* **New Partial Template:**
  - Add `plugin-modernizer-core/src/main/jte/partials/remove-developers-tag.jte` to include common text about the removal of the `developers` tag.
* **Update PR Body for `RemoveDevelopersTag`:**
  - Modify `plugin-modernizer-core/src/main/jte/pr-body-RemoveDevelopersTag.jte` to include the new partial template using the `include` directive.
* **Update PR Body for `UpgradeNextMajorParentVersion`:**
  - Modify `plugin-modernizer-core/src/main/jte/pr-body-UpgradeNextMajorParentVersion.jte` to include the new partial template using the `include` directive.

* fix(jte): No more partial templates.

* fix(jte): Missing 'Why is this important?' section ==> expected: <true> but was: <false>.

* fix(jte): Missing 'Why is this important?' section ==> expected: <true> but was: <false>.